### PR TITLE
Added rebuild.rake

### PR DESCRIPTION
**Pull request by jonpage**

### CODE REVIEW

**Comment by bentut** [comment]
Is this compare_forecasts stuff done as well? Looks like pretty substantial
changes to what's on there currently...

On Thu, Mar 20, 2014 at 12:19 PM, Jonathan Page notifications@github.comwrote:

> ---
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/jonpage/udaman master
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/bentut/udaman/pull/8
> Commit Summary
> - updating
> - added rebuild.rake
> - Added rebuild.rake
> 
> File Changes
> - _M_ app/views/data_lists/compare_forecasts.html.erbhttps://github.com/bentut/udaman/pull/8/files#diff-0(250)
> - _A_ lib/tasks/rebuild.rakehttps://github.com/bentut/udaman/pull/8/files#diff-1(19)
> 
> Patch Links:
> - https://github.com/bentut/udaman/pull/8.patch
> - https://github.com/bentut/udaman/pull/8.diff
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/bentut/udaman/pull/8
> .

## 

Ben Trevino....
808-225-4725

UHERO
The Economic Research Organization at the University of Hawaii
www.uhero.hawaii.edu | www.facebook.com/UHERO.forum
Database Manager
btrevino@hawaii.edu

INTERISLAND TERMINAL
Presenting international contemporary art, design and film /
Advancing the role of the arts in innovation
www.interislandterminal.org

**Comment by jonpage** [comment]
I have not worked on compare_forecasts in nearly a month. I don't think it
was done. But my version was different than your branch.
- Jon

**Comment by bentut** [comment]
hmm, so I shouldn't bring in the compare forecasts part of the pull request?
I wonder if I can pull in just the other file when I merge in the pull
request...

On Mon, Mar 24, 2014 at 3:04 PM, Jonathan Page notifications@github.comwrote:

> I have not worked on compare_forecasts in nearly a month. I don't think it
> was done. But my version was different than your branch.
> - Jon
> 
> On Monday, March 24, 2014, Benjamin Trevino notifications@github.com
> wrote:
> 
> > Is this compare_forecasts stuff done as well? Looks like pretty
> > substantial
> > changes to what's on there currently...
> > 
> > On Thu, Mar 20, 2014 at 12:19 PM, Jonathan Page <
> > notifications@github.com<javascript:_e(%7B%7D,'cvml','
> > notifications@github.com');>
> > 
> > > wrote:
> > > 
> > > ---
> > > 
> > > You can merge this Pull Request by running
> > > 
> > > git pull https://github.com/jonpage/udaman master
> > > 
> > > Or view, comment on, or merge it at:
> > > 
> > > https://github.com/bentut/udaman/pull/8
> > > Commit Summary
> > > - updating
> > > - added rebuild.rake
> > > - Added rebuild.rake
> > > 
> > > File Changes
> > > - _M_ app/views/data_lists/compare_forecasts.html.erb<
> > >   https://github.com/bentut/udaman/pull/8/files#diff-0>(250)
> > > - _A_ lib/tasks/rebuild.rake<
> > >   https://github.com/bentut/udaman/pull/8/files#diff-1>(19)
> > > 
> > > Patch Links:
> > > - https://github.com/bentut/udaman/pull/8.patch
> > > - https://github.com/bentut/udaman/pull/8.diff
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/bentut/udaman/pull/8>
> > > 
> > > .
> > 
> > ## 
> > 
> > Ben Trevino....
> > 808-225-4725
> > 
> > UHERO
> > The Economic Research Organization at the University of Hawaii
> > www.uhero.hawaii.edu | www.facebook.com/UHERO.forum
> > Database Manager
> > btrevino@hawaii.edu <javascript:_e(%7B%7D,'cvml','btrevino@hawaii.edu
> > ');>
> > 
> > INTERISLAND TERMINAL
> > Presenting international contemporary art, design and film /
> > Advancing the role of the arts in innovation
> > www.interislandterminal.org
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/bentut/udaman/pull/8#issuecomment-38520478>
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/bentut/udaman/pull/8#issuecomment-38520671
> .

## 

Ben Trevino....
808-225-4725

UHERO
The Economic Research Organization at the University of Hawaii
www.uhero.hawaii.edu | www.facebook.com/UHERO.forum
Database Manager
btrevino@hawaii.edu

INTERISLAND TERMINAL
Presenting international contemporary art, design and film /
Advancing the role of the arts in innovation
www.interislandterminal.org

**Comment by jonpage** [comment]
I'll close this and start a new pull request without the changes to compare_forecasts.

**Pull request closed without merging**
